# Generated by Django 5.0.14 on 2025-12-30 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_cases", "0002_rename_tag_label"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("test_execution", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestScenario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        related_name="created_scenarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "labels",
                    models.ManyToManyField(blank=True, related_name="scenarios", to="test_cases.label"),
                ),
                (
                    "test_cases",
                    models.ManyToManyField(blank=True, related_name="scenarios", to="test_cases.testcase"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        related_name="updated_scenarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveIndex(
            model_name="testrun",
            name="test_execut_status_0f0d6c_idx",
        ),
        migrations.AddField(
            model_name="testrun",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.SET_NULL,
                related_name="created_test_runs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="testrun",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="testrun",
            name="labels",
            field=models.ManyToManyField(blank=True, related_name="test_runs", to="test_cases.label"),
        ),
        migrations.AddField(
            model_name="testrun",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="testrun",
            name="scenarios",
            field=models.ManyToManyField(blank=True, related_name="test_runs", to="test_execution.testscenario"),
        ),
        migrations.AddField(
            model_name="testrun",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.SET_NULL,
                related_name="updated_test_runs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="testrun",
            name="board",
        ),
        migrations.RemoveField(
            model_name="testrun",
            name="initiated_by",
        ),
        migrations.RemoveField(
            model_name="testrun",
            name="output_log",
        ),
        migrations.RemoveField(
            model_name="testrun",
            name="status",
        ),
        migrations.RemoveField(
            model_name="testrun",
            name="started_at",
        ),
        migrations.RemoveField(
            model_name="testrun",
            name="test_case",
        ),
        migrations.RemoveField(
            model_name="testrun",
            name="finished_at",
        ),
    ]
