# Generated by Django 5.0.14 on 2025-12-30 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_cases", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tag",
            new_name="Label",
        ),
    ]
