# Generated by Django 5.0.14 on 2025-12-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testpc",
            name="auth_token",
            field=models.CharField(blank=True, default="", help_text="Token used to authenticate with the PC", max_length=200),
        ),
        migrations.AddField(
            model_name="testpc",
            name="workarea",
            field=models.CharField(blank=True, default="", help_text="Logical work area name/location", max_length=50),
        ),
    ]
